apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: ghcr.io/ailaephos/uvod-u-dev-ops/ticketing-worker:latest
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: postgres-secret
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
          livenessProbe:
            exec:
              command:
                - pgrep
                - -f
                - "node src/worker.js"
            initialDelaySeconds: 5
            periodSeconds: 10